image: python:3.10-bookworm

stages:
  - test

test:
  stage: test
  script:
    - python -m pip install --upgrade pip
    - python -m pip install pytest==8.* pytest-timeout==2.*
    - pytest --timeout=1 tests/
