[project]
name = "pykumir"
version = "1.0.0a0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "lark==1.2.2",
    "Pygments==2.19.1",
    "PySide6==6.9.0",
    # DEBUG
    "pytest==7.4.0",
]
