[project]
name = "pykumir"
version = "1.0.0a"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "Pygments>=2.2",
    "PyQt6",
    # DEBUG
    "pytest==7.4.*",
]
