[project]
name = "pykumir"
version = "1.0.0a"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "Pygments>=2.2",
    "PyQt6"
]

[dependency-groups]
dev = [
    "pytest==8.*",
    "pytest-cov==6.*",
    "pytest-timeout==2.*"
]
