#!/usr/bin/python3
import os
import sys

if __name__ == '__main__':
    if len(sys.argv) == 2 and sys.argv[1].endswith('.kum') and not (sys.stdin and sys.stdin.isatty()):
        file = 'main.py'
    elif len(sys.argv) >= 2:
        file = 'cli.py'
    else:
        file = 'main.py'
    command = f'/usr/bin/python3 /usr/lib/pykumir/src/{file} ' + ' '.join(sys.argv[1:])

    os.system(command)
