name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo apt-get update
      - name: Build
        run: |
          echo *
          dpkg-deb -b debian pykumir.deb
      - name: Install gh cli
        uses: sersoft-gmbh/setup-gh-cli-action@v2
        with:
          version: stable
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete existing release
        run: gh release delete ${{ github.ref_name }}.1.0.0a --cleanup-tag || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Wait a few moments...
        run: |
          sleep 20
      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          artifacts: 'pykumir.deb'
          tag: '1.0.0a'
          commit: ${{ github.sha }}
          artifactErrorsFailBuild: true
          makeLatest: true
